---
- name: Install User Local Ruby
  community.general.homebrew:
    name: ruby
  when: ansible_facts.distribution == 'MacOSX'

- name: Link Ruby Zsh Configuration
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/ruby/ruby.zsh"
    dest: "{{ ansible_facts.user_dir }}/.oh-my-zsh/custom/ruby.zsh"
