---
- name: Install User Local Ruby
  community.general.homebrew:
    name: ruby
  when: is_macos

- name: Link Ruby Zsh Configuration
  ansible.builtin.include_tasks:
    file: "{{ dotfiles_dir }}/includes/link_zsh_config.yml"
  vars:
    zsh_config_name: Ruby
    zsh_config_src: ruby/ruby.zsh
    zsh_config_dest: ruby.zsh
