---
# Git configuration (safe for all environments)
- name: Link gitconfig
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/git/gitconfig"
    dest: "{{ ansible_facts.user_dir }}/.gitconfig"
    force: yes

- name: Link gitconfig-pixee
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/gitconfig-pixee"
    dest: "{{ ansible_facts.user_dir }}/.gitconfig-pixee"
    force: yes

- name: Install gitmoji
  community.general.homebrew:
    name: gitmoji
  when: ansible_facts.distribution == 'MacOSX'

- name: Install git-absorb
  community.general.homebrew:
    name: git-absorb
  when: ansible_facts.distribution == 'MacOSX'
