---
- hosts: localhost
  connection: local
  tasks:
    - include_tasks: core.yml
    - include_tasks: zsh/zsh.yml
    - include_tasks: java/java.yml
    - include_tasks: ruby/ruby.yml
    - include_tasks: vim/vim.yml
    - include_tasks: macos/macos.yml
      when: ansible_distribution == 'MacOSX'
