#!/usr/bin/env ruby

# http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen
# Establishes a package manager like system for updating Vim bundles 
#  git://github.com/Lokaltog/vim-powerline.git
# from Github using Pathogen

git_bundles = %w{
  git://github.com/tpope/vim-markdown.git
  git://github.com/vim-ruby/vim-ruby.git
  git://github.com/scrooloose/syntastic.git
}

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.rm_rf(bundles_dir)
FileUtils.mkdir(bundles_dir)
FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  puts url
  `git clone -q #{url}`
end

Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }

