---
- name: Create Dedicated Screenshots Directory
  ansible.builtin.file:
    path: "{{ home_dir }}/Desktop/sshots"
    state: directory
    mode: "0755"


- name: Save Screenshots to Dedicated Directory
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: location
    value: "{{ home_dir }}/Desktop/sshots"


- name: Link inputrc
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/macos/inputrc"
    dest: "{{ home_dir }}/.inputrc"


- name: Development Source Tree Directory
  ansible.builtin.file:
    path: "{{ home_dir }}/development"
    state: directory
    mode: "0700"


- name: Exclude Development Tree From Spotlight Indexing
  ansible.builtin.copy:
    dest: "{{ home_dir }}/development/.metadata_never_index"
    content: ""
    force: false
    mode: "0644"


- name: Create Dracula Dir If Not Exists
  ansible.builtin.file:
    path: "{{ home_dir }}/dracula"
    state: directory
    mode: "0755"


- name: Link macOS Zsh Configuration
  ansible.builtin.include_tasks:
    file: "{{ dotfiles_dir }}/includes/link_zsh_config.yml"
  vars:
    zsh_config_name: macOS
    zsh_config_src: macos/macos.zsh
    zsh_config_dest: macos.zsh


- name: Core Brew Packages
  community.general.homebrew:
    name:
      - coreutils
      - curl
      - dos2unix
      - fzf
      - gnu-sed
      - gnu-tar
      - jq
      - lastpass-cli
      - p7zip
      - ripgrep
      - tree
      - vim
      - watch
      - wget
      - z
