---
# Core configuration module - basic directories and dotfiles
- name: User bin
  ansible.builtin.file:
    path: "{{ home_dir }}/bin"
    state: directory
    mode: "0755"

- name: Development Tools Directory
  ansible.builtin.file:
    path: "{{ home_dir }}/devtools"
    state: directory
    mode: "0755"

- name: Link basic dotfiles
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/{{ item }}"
    dest: "{{ home_dir }}/.{{ item }}"
    force: true
  loop:
    - ackrc
    - screenrc

- name: Bin Scripts Dir
  ansible.builtin.file:
    state: directory
    path: "{{ home_dir }}/bin"
    mode: "0755"

- name: Bin Scripts
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/bin/{{ item }}"
    dest: "{{ home_dir }}/bin/{{ item }}"
  loop:
    - echo-server.py
    - gh-prune-notifications
    - tcp-proxy.sh

- name: Set Terminal Directory Color Scheme  # noqa: latest[git]
  ansible.builtin.git:
    repo: https://github.com/seebi/dircolors-solarized
    dest: "{{ home_dir }}/.dircolors"
    depth: 1
    version: HEAD
