---
- name: Install OpenJDK LTS
  community.general.homebrew_cask:
    name:
      - temurin@17
      - temurin@21
      - temurin
  when: is_macos


- name: Install Maven
  community.general.homebrew:
    name: maven
  when: is_macos


- name: Install Eclipse JDT Language Server
  community.general.homebrew:
    name: jdtls
  when: is_macos


- name: Tap GNG
  community.general.homebrew_tap:
    name: gdubw/gng
  when: is_macos


- name: Install GNG
  community.general.homebrew:
    name: gng
  when: is_macos


- name: Link Java Zsh Configuration
  ansible.builtin.include_tasks:
    file: "{{ dotfiles_dir }}/includes/link_zsh_config.yml"
  vars:
    zsh_config_name: Java
    zsh_config_src: java/java.zsh
    zsh_config_dest: java.zsh
