---
- name: Install OpenJDK LTS
  community.general.homebrew_cask:
    name:
      - temurin@17
      - temurin@21
      - temurin
  when: ansible_facts.distribution == 'MacOSX'


- name: Install Maven
  community.general.homebrew:
    name: maven
  when: ansible_facts.distribution == 'MacOSX'


- name: Install Eclipse JDT Language Server
  community.general.homebrew:
    name: jdtls
  when: ansible_facts.distribution == 'MacOSX'


- name: Tap GNG
  community.general.homebrew_tap:
    name: gdubw/gng
  when: ansible_facts.distribution == 'MacOSX'


- name: Install GNG
  community.general.homebrew:
    name: gng
  when: ansible_facts.distribution == 'MacOSX'


- name: Link Java Zsh Configuration
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/java/java.zsh"
    dest: "{{ ansible_facts.user_dir }}/.oh-my-zsh/custom/java.zsh"
