---
- name: Install AWS CLI
  community.general.homebrew:
    name: awscli
  when: is_macos


- name: Install Amazon ECR Docker Credential Helper
  community.general.homebrew:
    name: docker-credential-helper-ecr
  when: is_macos
  notify: Print ECR Docker configuration instructions


- name: Install aws-ssm-ec2-proxy-command  # noqa: latest[git]
  ansible.builtin.git:
    repo: https://github.com/qoomon/aws-ssm-ssh-proxy-command.git
    dest: "{{ home_dir }}/devtools/aws-ssm-ssh-proxy-command"
    depth: 1
    version: HEAD


- name: Make aws-ssm-ec2-proxy-command Executable
  ansible.builtin.file:
    path: "{{ home_dir }}/devtools/aws-ssm-ssh-proxy-command/aws-ssm-ssh-proxy-command.sh"
    mode: "0750"


- name: Configure SSH
  ansible.builtin.copy:
    src: ec2-ssm
    dest: "{{ home_dir }}/.ssh/config.d/ec2-ssm"
    mode: "0600"


- name: Link AWS Zsh Configuration
  ansible.builtin.include_tasks:
    file: "{{ dotfiles_dir }}/includes/link_zsh_config.yml"
  vars:
    zsh_config_name: AWS
    zsh_config_src: aws/aws.zsh
    zsh_config_dest: aws.zsh
