---
- name: Link Visual Studio Code Zsh Configuration
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/vscode/vscode.zsh"
    dest: "{{ ansible_facts.user_dir }}/.oh-my-zsh/custom/vscode.zsh"
