---
- name: Install just
  community.general.homebrew:
    name: just
  when: ansible_facts.distribution == 'MacOSX'


- name: Link just ZSH completions
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/just/just.zsh"
    dest: "{{ ansible_facts.user_dir }}/.oh-my-zsh/custom/just.zsh"
