---

- name: Install docuum
  community.general.homebrew:
    name: docuum
  when: is_macos


- name: Add LaunchAgents if not exists
  ansible.builtin.file:
    path: "{{ home_dir }}/Library/LaunchAgents"
    state: directory
    mode: 0755


- name: Configure docuum Launch Agent
  ansible.builtin.template:
    src: com.github.stepchowfun.docuum.plist.j2
    dest: "{{ home_dir }}/Library/LaunchAgents/com.github.stepchowfun.docuum.plist"
    mode: 0644
  when: is_macos


- name: Enable doccum launchd Service
  ansible.builtin.command: "launchctl load {{ home_dir }}/Library/LaunchAgents/com.github.stepchowfun.docuum.plist"
  become: yes
  when: is_macos
