---

- name: Install docuum
  community.general.homebrew:
    name: docuum
  when: ansible_facts.distribution == 'MacOSX'


- name: Add LaunchAgents if not exists
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/Library/LaunchAgents"
    state: directory
    mode: 0755


- name: Configure docuum Launch Agent
  ansible.builtin.template:
    src: com.github.stepchowfun.docuum.plist.j2
    dest: "{{ ansible_facts.user_dir }}/Library/LaunchAgents/com.github.stepchowfun.docuum.plist"
    mode: 0644
  when: ansible_facts.distribution == 'MacOSX'


- name: Enable doccum launchd Service
  ansible.builtin.command: "launchctl load {{ ansible_facts.user_dir}}/Library/LaunchAgents/com.github.stepchowfun.docuum.plist"
  become: yes
  when: ansible_facts.distribution == 'MacOSX'
