---
# Git identity and signing configuration
- name: Link gitconfig-identity
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/gitconfig-identity"
    dest: "{{ home_dir }}/.gitconfig-identity"
    force: yes
