---
- name: Install GitHub CLI
  community.general.homebrew:
    name: gh
  when: is_macos


- name: Configure SSH for GitHub Codespaces
  ansible.builtin.copy:
    src: codespaces
    dest: "{{ home_dir }}/.ssh/config.d/codespaces"
    mode: "0600"
