---
- name: Install pyenv
  community.general.homebrew:
    name: pyenv
  when: ansible_facts.distribution == 'MacOSX'


- name: Install pipx
  community.general.homebrew:
    name: pipx
  when: ansible_facts.distribution == 'MacOSX'


- name: Install uv
  community.general.homebrew:
    name: uv
  when: ansible_facts.distribution == 'MacOSX'


- name: Install ansible-lint
  community.general.homebrew:
    name: ansible-lint
  when: ansible_facts.distribution == 'MacOSX'


- name: Link Python Zsh Configuration
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/python/python.zsh"
    dest: "{{ ansible_facts.user_dir }}/.oh-my-zsh/custom/python.zsh"
