---
- name: Install pyenv
  community.general.homebrew:
    name: pyenv
  when: is_macos


- name: Install pipx
  community.general.homebrew:
    name: pipx
  when: is_macos


- name: Install uv
  community.general.homebrew:
    name: uv
  when: is_macos


- name: Install ansible-lint
  community.general.homebrew:
    name: ansible-lint
  when: is_macos


- name: Link Python Zsh Configuration
  ansible.builtin.include_tasks:
    file: "{{ dotfiles_dir }}/includes/link_zsh_config.yml"
  vars:
    zsh_config_name: Python
    zsh_config_src: python/python.zsh
    zsh_config_dest: python.zsh
