source ~/.bash_aliases

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

PS1="\W\$(__git_ps1) \$ "

export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home

# Going to give Mavericks the benefit of the doubt and disable the following JAVA_TOOL_OPTIONS export
# export JAVA_TOOL_OPTIONS='-Djava.awt.headless=true' # Stop the Java forking madness in OS X!! Switches desktop focus every time a Java process is launched

export MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=256m -Xss1024k"

export GRAILS_HOME="~/devtools/grails/grails-1.3.7/bin"

export ANT_HOME="~/devtools/ant"

export MYSQL_HOME="/usr/local/mysql/bin"

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
PATH=$PATH:$HOME/devtools/groovy/bin
PATH=$PATH:$GRAILS_HOME
PATH=$PATH:/usr/local/bin
PATH=$PATH:$HOME/devtools/jmeter/bin
PATH=$PATH:$HOME/devtools/sbt/bin
PATH=$PATH:$HOME/devtools/maven/bin
PATH=$PATH:$ANT_HOME/bin
PATH=$PATH:$MYSQL_HOME
PATH=$PATH:/usr/local/lib/node_modules/karma/bin

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

function ancestor()
{
  (~/dotfiles/ancestor.rb $1) && cd $(~/dotfiles/ancestor.rb $1)
}


### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
