---
- name: Check if .zshrc exists
  ansible.builtin.stat:
    path: "{{ ansible_facts.user_dir }}/.zshrc"
  register: zshrc_stat

- name: Backup existing .zshrc in Codespaces
  ansible.builtin.copy:
    src: "{{ ansible_facts.user_dir }}/.zshrc"
    dest: "{{ ansible_facts.user_dir }}/.zshrc.codespaces-backup"
    remote_src: yes
  when:
    - zshrc_stat.stat.exists
    - lookup('env', 'CODESPACES') == 'true'

- name: Install Oh My ZSH
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_facts.user_dir }}/.oh-my-zsh"


- name: Link zshrc
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/zsh/zshrc"
    dest: "{{ ansible_facts.user_dir }}/.zshrc"
    force: yes


- name: Link zprofile
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/zsh/zprofile"
    dest: "{{ ansible_facts.user_dir }}/.zprofile"
    force: yes


- name: Link Aliases and Functions
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/zsh/aliases.zsh"
    dest: "{{ ansible_facts.user_dir }}/.oh-my-zsh/custom/aliases.zsh"


- name: Link Theme
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/zsh/gilday.zsh-theme"
    dest: "{{ ansible_facts.user_dir }}/.oh-my-zsh/custom/gilday.zsh-theme"


- name: Install logcli plugin
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/zsh/plugins/logcli"
    dest: "{{ ansible_facts.user_dir }}/.oh-my-zsh/custom/plugins/logcli"


- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_facts.user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"


- name: Create Dracula Dir If Not Exists
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/dracula"
    state: directory
    mode: 0755


- name: Download Dracula Theme
  ansible.builtin.git:
    repo: https://github.com/dracula/zsh.git
    dest: "{{ ansible_facts.user_dir }}/dracula/zsh"


- name: Install Dracula Theme
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.oh-my-zsh/themes/dracula.zsh-theme"
    state: link
    src: "{{ ansible_facts.user_dir }}/dracula/zsh/dracula.zsh-theme"
