# OH MY ZSH
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="gilday"

# Use case sensitive completion
CASE_SENSITIVE="true"

# Disable marking untracked files under VCS as dirty. This makes repository
# status check for large repositories much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# ISO 8601 dates in history
HIST_STAMPS="yyyy-mm-dd"

# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git ssh-agent)

# enable tmux friendly ssh forwarding auth socket
# this setting does not actually enable agent forwarding
zstyle :omz:plugins:ssh-agent agent-forwarding on
source $ZSH/oh-my-zsh.sh


# EDITOR
export EDITOR=nvim


# PATH
# unique entries in path array
typeset -U path
path+=$HOME/bin
