# OH MY ZSH
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="dracula"

# Use case sensitive completion
CASE_SENSITIVE="true"

# Disable marking untracked files under VCS as dirty. This makes repository
# status check for large repositories much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# ISO 8601 dates in history
HIST_STAMPS="yyyy-mm-dd"

# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(
  docker
  git
  ssh-agent
  vi-mode
  pyenv
  zsh-autosuggestions
  1password
)

# enable tmux friendly ssh forwarding auth socket
# this setting does not actually enable agent forwarding
zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent lazy yes
source $ZSH/oh-my-zsh.sh


# EDITOR
export EDITOR=vim


# PATH
# unique entries in path array
typeset -U path
path+=$HOME/bin


# ZSH Line Editor
# macbook keyboard delete button
bindkey '^[[3~' delete-char


# HISTORY
# share history across multiple zsh sessions
setopt SHARE_HISTORY
# append to history
setopt APPEND_HISTORY
# adds commands as they are typed, not at shell exit
setopt INC_APPEND_HISTORY
# removes blank lines from history
setopt HIST_REDUCE_BLANKS
