---
- name: Install 1Password CLI
  community.general.homebrew:
    name: 1password-cli
  when: ansible_facts.distribution == 'MacOSX'


- name: Link 1Password Zsh Configuration
  ansible.builtin.file:
    state: link
    src: "{{ dotfiles_dir }}/1password/1password.zsh"
    dest: "{{ ansible_facts.user_dir }}/.oh-my-zsh/custom/1password.zsh"
