---
- name: Install 1Password CLI
  community.general.homebrew:
    name: 1password-cli
  when: is_macos


- name: Link 1Password Zsh Configuration
  ansible.builtin.include_tasks:
    file: "{{ dotfiles_dir }}/includes/link_zsh_config.yml"
  vars:
    zsh_config_name: 1Password
    zsh_config_src: 1password/1password.zsh
    zsh_config_dest: 1password.zsh
